/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReturnsProcessor;

import Business.Business;
import Business.Enterprise;
import Business.Network;
import Business.Organization;
import Business.UserAccount;
//import UserInterface.ProductManager.ViewReportedSuspectDrugsJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bobba
 */
public class ReturnsProcessorJPanel extends javax.swing.JPanel {
    
    
    JPanel userProcessContainer;
    Business business;
    UserAccount userAccount;

    /**
     * Creates new form ReturnsProcessorJPanel
     */
    public ReturnsProcessorJPanel(JPanel userProcessContainer, Business business, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.userAccount=userAccount;
        
        
        
//        retrunLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ImageProcessor.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewDrugsReturendButton = new javax.swing.JButton();
        drugsToBeDisposedButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Returns Processor Work Area");

        viewDrugsReturendButton.setText("View Drugs Returned");
        viewDrugsReturendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDrugsReturendButtonActionPerformed(evt);
            }
        });

        drugsToBeDisposedButton.setText("Disposable Drugs");
        drugsToBeDisposedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugsToBeDisposedButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(126, 126, 126)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(160, 160, 160)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(viewDrugsReturendButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(drugsToBeDisposedButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jLabel1)
                .add(39, 39, 39)
                .add(viewDrugsReturendButton)
                .add(18, 18, 18)
                .add(drugsToBeDisposedButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewDrugsReturendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDrugsReturendButtonActionPerformed
        // TODO add your handling code here:
        
        
        for(Network network:business.getNetworkDirectory().getNetworkList())
        {
            for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList())
                
            {
                for(Organization organization:enterprise.getOrganizationDirectory().getOrgList())
                {
                for(UserAccount userAccount1:organization.getUserAccountDirectory().getUserAccountList())
                {
                    if(userAccount == userAccount1){
                        ViewDrugsReturnedJPanel viewDrugsReturnedJPanel=new ViewDrugsReturnedJPanel(userProcessContainer,network,userAccount);
                        userProcessContainer.add("viewretDrugs",viewDrugsReturnedJPanel);
                        CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
                        cardLayout.next(userProcessContainer);

                    }

                }
            }
        }
        }
    }//GEN-LAST:event_viewDrugsReturendButtonActionPerformed

    private void drugsToBeDisposedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugsToBeDisposedButtonActionPerformed
        // TODO add your handling code here:
         for(Network network:business.getNetworkDirectory().getNetworkList())
        {
            for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList())
                
            {
                for(Organization organization:enterprise.getOrganizationDirectory().getOrgList())
                {
                for(UserAccount userAccount1:organization.getUserAccountDirectory().getUserAccountList())
                {
                    if(userAccount == userAccount1){
                        ViewDrugsToBeDisposedJPanel viewDrugsToBeDisposedJPanel=new ViewDrugsToBeDisposedJPanel(userProcessContainer,network,userAccount);
                        userProcessContainer.add("viewdisdrgs",viewDrugsToBeDisposedJPanel);
                        CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
                        cardLayout.next(userProcessContainer);

                    }

                }
            }
        }
        }
    }//GEN-LAST:event_drugsToBeDisposedButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drugsToBeDisposedButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewDrugsReturendButton;
    // End of variables declaration//GEN-END:variables
}
