/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseAdmin;

import Business.Employee;
import Business.Enterprise;
import Business.Network;
import Business.Organization;
import Business.Roles.Role;
import Business.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nived
 */
public class AddUserAccountJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    UserAccount userAccount;

    /**
     * Creates new form AddUserAccountJPanel
     */
    public AddUserAccountJPanel(JPanel userProcessContainer, Network network, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.userAccount = userAccount;

        organizationJComboBox.removeAllItems();

        Enterprise e = network.getEnterpriseDirectory().getMyEnterprise(userAccount);
        organizationJComboBox.addItem((Organization) e);
        for (Organization org : e.getOrganizationDirectory().getOrgList()) {
            organizationJComboBox.addItem(org);
        }

        roleJComboBox.removeAllItems();
        for (Role role : e.getSupportedRoles()) {
            roleJComboBox.addItem(role);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addUserAccountJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        employeeJComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        passwordJTextField = new javax.swing.JTextField();
        roleJComboBox = new javax.swing.JComboBox();
        usernameJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(238, 238, 238));
        setMaximumSize(new java.awt.Dimension(1280, 700));
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setPreferredSize(new java.awt.Dimension(1280, 700));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 40, 49));
        jLabel3.setText("SELECT ORGANIZATION");

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 40, 49));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD DETAILS TO CREATE USER ACCOUNT");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 173, 181)));
        jLabel2.setMaximumSize(new java.awt.Dimension(210, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(210, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(210, 30));

        addUserAccountJButton.setBackground(new java.awt.Color(57, 62, 70));
        addUserAccountJButton.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        addUserAccountJButton.setForeground(new java.awt.Color(238, 238, 238));
        addUserAccountJButton.setText("ADD USER");
        addUserAccountJButton.setMaximumSize(new java.awt.Dimension(150, 33));
        addUserAccountJButton.setMinimumSize(new java.awt.Dimension(150, 33));
        addUserAccountJButton.setPreferredSize(new java.awt.Dimension(150, 33));
        addUserAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserAccountJButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 40, 49));
        jLabel6.setText("SELECT ROLE");

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 40, 49));
        jLabel4.setText("CREATE USERNAME");

        organizationJComboBox.setBackground(new java.awt.Color(238, 238, 238));
        organizationJComboBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        organizationJComboBox.setForeground(new java.awt.Color(34, 40, 49));
        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationJComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));
        organizationJComboBox.setMaximumSize(new java.awt.Dimension(200, 24));
        organizationJComboBox.setMinimumSize(new java.awt.Dimension(200, 24));
        organizationJComboBox.setPreferredSize(new java.awt.Dimension(200, 24));
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 40, 49));
        jLabel5.setText("CREATE PASSWORD");

        employeeJComboBox.setBackground(new java.awt.Color(238, 238, 238));
        employeeJComboBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        employeeJComboBox.setForeground(new java.awt.Color(34, 40, 49));
        employeeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        employeeJComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));
        employeeJComboBox.setMaximumSize(new java.awt.Dimension(200, 24));
        employeeJComboBox.setMinimumSize(new java.awt.Dimension(200, 24));
        employeeJComboBox.setPreferredSize(new java.awt.Dimension(200, 24));

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(34, 40, 49));
        jLabel7.setText("SELECT EMPLOYEE");

        backJButton.setBackground(new java.awt.Color(238, 238, 238));
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/back.png"))); // NOI18N
        backJButton.setBorder(null);
        backJButton.setMaximumSize(new java.awt.Dimension(60, 60));
        backJButton.setMinimumSize(new java.awt.Dimension(60, 60));
        backJButton.setPreferredSize(new java.awt.Dimension(60, 60));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        passwordJTextField.setBackground(new java.awt.Color(238, 238, 238));
        passwordJTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        passwordJTextField.setForeground(new java.awt.Color(34, 40, 49));
        passwordJTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));
        passwordJTextField.setMaximumSize(new java.awt.Dimension(200, 24));
        passwordJTextField.setMinimumSize(new java.awt.Dimension(200, 24));
        passwordJTextField.setPreferredSize(new java.awt.Dimension(200, 24));

        roleJComboBox.setBackground(new java.awt.Color(238, 238, 238));
        roleJComboBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        roleJComboBox.setForeground(new java.awt.Color(34, 40, 49));
        roleJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roleJComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));
        roleJComboBox.setMaximumSize(new java.awt.Dimension(200, 24));
        roleJComboBox.setMinimumSize(new java.awt.Dimension(200, 24));
        roleJComboBox.setPreferredSize(new java.awt.Dimension(200, 24));

        usernameJTextField.setBackground(new java.awt.Color(238, 238, 238));
        usernameJTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        usernameJTextField.setForeground(new java.awt.Color(34, 40, 49));
        usernameJTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));
        usernameJTextField.setMaximumSize(new java.awt.Dimension(200, 24));
        usernameJTextField.setMinimumSize(new java.awt.Dimension(200, 24));
        usernameJTextField.setPreferredSize(new java.awt.Dimension(200, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addUserAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(roleJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(employeeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usernameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(organizationJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(employeeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(addUserAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void addUserAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserAccountJButtonActionPerformed

        Organization organization = (Organization) organizationJComboBox.getSelectedItem();
        Employee employee = (Employee) employeeJComboBox.getSelectedItem();

        if (!usernameJTextField.getText().isEmpty() && !passwordJTextField.getText().isEmpty()) {
            if (!network.getEnterpriseDirectory().isUserExisting(usernameJTextField.getText())) {
                if (passwordPattern() == true) {

                    UserAccount ua = organization.getUserAccountDirectory().newAccount();
                    ua.setUserName(usernameJTextField.getText());
                    ua.setPassword(passwordJTextField.getText());

                    Role role = (Role) roleJComboBox.getSelectedItem();
                    ua.setRole(role);

                    ua.setEmployee(employee);

                    JOptionPane.showMessageDialog(this, "UserAccount Added");

                    usernameJTextField.setText("");
                    passwordJTextField.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, "
                            + "one lower case letter, one digit and one special character $, *, # or &.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "User Name already present");
            }
        } else {

            JOptionPane.showMessageDialog(this, "UserName/Password cannot be left blank");
        }

    }//GEN-LAST:event_addUserAccountJButtonActionPerformed

    private boolean passwordPattern() {
        Pattern p = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m = p.matcher(passwordJTextField.getText());
        boolean b = m.matches();
        return b;
    }

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:

        Organization organization = (Organization) organizationJComboBox.getSelectedItem();

        if (organization != null) {
            employeeJComboBox.removeAllItems();
            for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {
                employeeJComboBox.addItem(employee);
            }
        }
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserAccountJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox employeeJComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTextField passwordJTextField;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
