/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseAdmin;

import Business.Business;
import Business.Enterprise;
import Business.Network;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author nived
 */
public class EnterpriseAdminJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Business business;
    UserAccount userAccount;

    /**
     * Creates new form EnterpriseAdminJPanel
     */
    public EnterpriseAdminJPanel(JPanel userProcessContainer,Business business,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.userAccount=userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageEmployeeButton = new javax.swing.JButton();
        manageUserAccountButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(238, 238, 238));
        setMaximumSize(new java.awt.Dimension(1280, 700));
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setPreferredSize(new java.awt.Dimension(1280, 700));

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 40, 49));
        jLabel1.setText("Enterprise Admin Work-Area");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 173, 181)));

        manageEmployeeButton.setBackground(new java.awt.Color(57, 62, 70));
        manageEmployeeButton.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        manageEmployeeButton.setForeground(new java.awt.Color(238, 238, 238));
        manageEmployeeButton.setText("MANAGE EMPLOYEE");
        manageEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeButtonActionPerformed(evt);
            }
        });

        manageUserAccountButton.setBackground(new java.awt.Color(57, 62, 70));
        manageUserAccountButton.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        manageUserAccountButton.setForeground(new java.awt.Color(238, 238, 238));
        manageUserAccountButton.setLabel("MANAGE USER ACCOUNT");
        manageUserAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(497, 497, 497)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(manageEmployeeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(manageUserAccountButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(497, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(150, 150, 150)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(100, 100, 100)
                .add(manageEmployeeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(50, 50, 50)
                .add(manageUserAccountButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeButtonActionPerformed
        // TODO add your handling code here:
        for(Network network:business.getNetworkDirectory().getNetworkList())
        {
            for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList())
            {
            for(UserAccount userAccount1:enterprise.getUserAccountDirectory().getUserAccountList())
                
            {
                
            if(userAccount == userAccount1)
            {
        
        ManageEmployeeJPanel manageEmployeeJPanel=new ManageEmployeeJPanel(userProcessContainer,network,userAccount);
        userProcessContainer.add("ManageEmployee",manageEmployeeJPanel);
        
        CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
            }
        }
        }
        }
    }//GEN-LAST:event_manageEmployeeButtonActionPerformed

    private void manageUserAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountButtonActionPerformed
        // TODO add your handling code here:
      for(Network network:business.getNetworkDirectory().getNetworkList())
        {
            for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList())
            {
            for(UserAccount userAccount1:enterprise.getUserAccountDirectory().getUserAccountList())
                
            {
                
            if(userAccount == userAccount1)
            {  
        ManageUserAccountJPanel manageUserAccountJPanel=new ManageUserAccountJPanel(userProcessContainer,network, userAccount);
        userProcessContainer.add("ManageUserAccount",manageUserAccountJPanel);
        
        CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
                }
            }
        }
        }
    }//GEN-LAST:event_manageUserAccountButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmployeeButton;
    private javax.swing.JButton manageUserAccountButton;
    // End of variables declaration//GEN-END:variables
}
