/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductManager;

import Business.Business;
import Business.Enterprise;
import Business.ManufacturerEnterprise;
import Business.Network;
import Business.Organization;
import Business.Transaction;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author srush
 */
public class ProductManagerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Business business;
    UserAccount userAccount;

    /**
     * Creates new form ProductManagerJPanel
     */
    public ProductManagerJPanel(JPanel userProcessContainer, Business business, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
        infoLabel.setVisible(false);
        refresh();

    }

    public void refresh() {
        for (Network network : business.getNetworkDirectory().getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise.getClass().equals(ManufacturerEnterprise.class)) {

                    ManufacturerEnterprise manufacturerEnterprise = (ManufacturerEnterprise) enterprise;

                    for (Transaction transaction : network.getTransactionHistory().getTransactionList()) {

                        if (transaction.getManufacturerEnterprise() == null) {
                            return;
                        }
                        if (transaction.getManufacturerEnterprise().getEnterpriseName() == manufacturerEnterprise.getEnterpriseName()) {
                            if (transaction.getPackage().getPackageStatus().equalsIgnoreCase("Illegetimate Drug")) {
                                infoLabel.setVisible(true);
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addDrugsBtn = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 238, 238));
        setMaximumSize(new java.awt.Dimension(1280, 700));
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setPreferredSize(new java.awt.Dimension(1280, 700));

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 40, 49));
        jLabel1.setText("Product Manager Work Area");

        addDrugsBtn.setBackground(new java.awt.Color(0, 173, 181));
        addDrugsBtn.setForeground(new java.awt.Color(34, 40, 49));
        addDrugsBtn.setText("Add Drugs");
        addDrugsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugsBtnActionPerformed(evt);
            }
        });

        infoLabel.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(232, 69, 69));
        infoLabel.setText("* Drugs produced are reported illegetimate *");
        infoLabel.setToolTipText("");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(453, 453, 453)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(addDrugsBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(infoLabel))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(200, 200, 200)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(50, 50, 50)
                .add(addDrugsBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 170, Short.MAX_VALUE)
                .add(infoLabel)
                .add(200, 200, 200))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDrugsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugsBtnActionPerformed
        // TODO add your handling code here:
        AddDrugJPanel addDrugJPanel = new AddDrugJPanel(userProcessContainer, business, userAccount);
        userProcessContainer.add("AddDrugJPanel", addDrugJPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_addDrugsBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrugsBtn;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
