/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductManager;

import Business.Business;
import Business.Drug;
import Business.Enterprise;
import Business.ManufacturerEnterprise;
import Business.Network;
import Business.Organization;
import Business.Transaction;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srush
 */
public class ProductManagerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Business business;
    UserAccount userAccount;

    /**
     * Creates new form ProductManagerJPanel
     */
    public ProductManagerJPanel(JPanel userProcessContainer, Business business, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
        infoLabel.setVisible(false);
        refresh();
        Refresh();

    }

    public void refresh() {
        for (Network network : business.getNetworkDirectory().getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise.getClass().equals(ManufacturerEnterprise.class)) {

                    ManufacturerEnterprise manufacturerEnterprise = (ManufacturerEnterprise) enterprise;

                    for (Transaction transaction : network.getTransactionHistory().getTransactionList()) {

                        if (transaction.getManufacturerEnterprise() == null) {
                            return;
                        }
                        if (transaction.getManufacturerEnterprise().getEnterpriseName() == manufacturerEnterprise.getEnterpriseName()) {
                            if (transaction.getPackage().getPackageStatus().equalsIgnoreCase("Illegetimate Drug")) {
                                infoLabel.setVisible(true);
                            }
                        }
                    }
                }
            }
        }
    }

    public void Refresh() {

        int rowCount = drugCatalogJTable.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) drugCatalogJTable.getModel()).removeRow(i);
        }
        for (Network network : business.getNetworkDirectory().getNetworkList()) {
            Enterprise enterprise = network.getEnterpriseDirectory().getMyEnterprise(userAccount);
            ManufacturerEnterprise manufacturerEnterprise = (ManufacturerEnterprise) enterprise;
            Object row[] = new Object[4];
            for (Drug drug : manufacturerEnterprise.getDrugCatalog().getDrugList()) {
                row[0] = drug.getDrugID();
                row[1] = drug.getDrugName();
                row[2] = drug.getDrugContents();
                row[3] = drug.getDrugFor();
                ((DefaultTableModel) drugCatalogJTable.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addDrugsBtn = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugCatalogJTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(238, 238, 238));
        setMaximumSize(new java.awt.Dimension(1280, 700));
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setPreferredSize(new java.awt.Dimension(1280, 700));

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 40, 49));
        jLabel1.setText("PRODUCT MANAGER WORK-AREA");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 173, 181)));

        addDrugsBtn.setBackground(new java.awt.Color(57, 62, 70));
        addDrugsBtn.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        addDrugsBtn.setForeground(new java.awt.Color(238, 238, 238));
        addDrugsBtn.setText("ADD DRUGS");
        addDrugsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugsBtnActionPerformed(evt);
            }
        });

        infoLabel.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(232, 69, 69));
        infoLabel.setText("* DRUGS PRODUCED ARE REPORTED ILLEGETIMATE *");
        infoLabel.setToolTipText("");

        drugCatalogJTable.setBackground(new java.awt.Color(238, 238, 238));
        drugCatalogJTable.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        drugCatalogJTable.setForeground(new java.awt.Color(34, 40, 49));
        drugCatalogJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "Content", "Purpose"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        drugCatalogJTable.setGridColor(new java.awt.Color(34, 40, 49));
        drugCatalogJTable.setMaximumSize(new java.awt.Dimension(680, 122));
        drugCatalogJTable.setMinimumSize(new java.awt.Dimension(680, 122));
        drugCatalogJTable.setName(""); // NOI18N
        drugCatalogJTable.setPreferredSize(new java.awt.Dimension(680, 122));
        drugCatalogJTable.setRowHeight(22);
        drugCatalogJTable.setSelectionBackground(new java.awt.Color(0, 173, 181));
        drugCatalogJTable.setSelectionForeground(new java.awt.Color(238, 238, 238));
        jScrollPane1.setViewportView(drugCatalogJTable);

        refreshButton.setBackground(new java.awt.Color(238, 238, 238));
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/refresh.png"))); // NOI18N
        refreshButton.setBorder(null);
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(refreshButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(300, 300, 300)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 680, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(503, 503, 503)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(addDrugsBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(302, 302, 302))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel1)
                        .addContainerGap(502, Short.MAX_VALUE))))
            .add(layout.createSequentialGroup()
                .add(464, 464, 464)
                .add(infoLabel)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(120, 120, 120)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(20, 20, 20)
                .add(refreshButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(20, 20, 20)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30)
                .add(addDrugsBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 156, Short.MAX_VALUE)
                .add(infoLabel)
                .add(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDrugsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugsBtnActionPerformed
        // TODO add your handling code here:
        AddDrugJPanel addDrugJPanel = new AddDrugJPanel(userProcessContainer, business, userAccount);
        userProcessContainer.add("AddDrugJPanel", addDrugJPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_addDrugsBtnActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        Refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrugsBtn;
    private javax.swing.JTable drugCatalogJTable;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
