/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LawEnforcementOfficer;

import Business.DistributorEnterprise;
import Business.Enterprise;
import Business.HospitalEnterprise;
import Business.InventoryItem;
import Business.WorkRequests.LawEnforcementInspectorWorkRequest;
import Business.ManufacturerEnterprise;
import Business.Network;
import Business.Package1;
import Business.Doctor;
import Business.Transaction;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author srush
 */
public class ViewTransactionDetailsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LawEnforcementInspectorWorkRequest lawEnforcementInspectorWorkRequest;
    Network network;
    UserAccount userAccount;

    /**
     * Creates new form ViewTransactionDetailsJPanel
     */
    public ViewTransactionDetailsJPanel(JPanel userProcessContainer, LawEnforcementInspectorWorkRequest lawEnforcementInspectorWorkRequest, Network network, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.lawEnforcementInspectorWorkRequest = lawEnforcementInspectorWorkRequest;
        this.network = network;
        this.userAccount = userAccount;
        manuField.setEditable(false);
        distField.setEditable(false);
        dispenserNameField.setEditable(false);
        packIdField.setEditable(false);
        statusField.setEditable(false);
        statusField.setText("Illegetimate Drug");
        patientField.setEditable(false);

        refresh();

    }

    public void refresh() {

        for (Transaction transaction : network.getTransactionHistory().getTransactionList()) {
            if (transaction.getPackage().getPackageID() == lawEnforcementInspectorWorkRequest.getPackage1().getPackageID()) {
                manuField.setText(transaction.getManufacturerEnterprise().getEnterpriseName());
                distField.setText(transaction.getDistributorEnterprise().getEnterpriseName());
                if (transaction.getHospitalEnterprise() == null) {
                    dispenserNameField.setText("");
                } else {
                    dispenserNameField.setText(transaction.getHospitalEnterprise().getEnterpriseName());
                }

                //dispenserNameField.setText(transaction.getDispenser().getEnterpriseName());
                packIdField.setText(Integer.toString(transaction.getPackage().getPackageID()));
                if (transaction.getDoctor() == null) {
                    patientField.setText("");
                } else {
                    patientField.setText(transaction.getDoctor().getFirstName());
                }

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        manuField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        distField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dispenserNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        packIdField = new javax.swing.JTextField();
        sendEmerReportButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        statusField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        patientField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("View Transaction Details");

        jLabel2.setText("Manufacturer Name:");

        jLabel3.setText("Distributor Name:");

        jLabel4.setText("Dispenser Name:");

        jLabel5.setText("Package ID:");

        sendEmerReportButton.setBackground(new java.awt.Color(255, 51, 51));
        sendEmerReportButton.setText("Send Emergency Report");
        sendEmerReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmerReportButtonActionPerformed(evt);
            }
        });

        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Status:");

        jLabel7.setText("Doctor Name:");

        patientField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sendEmerReportButton)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(patientField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(statusField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(packIdField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addComponent(dispenserNameField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(distField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(manuField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(manuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(distField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dispenserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(patientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(packIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(sendEmerReportButton)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendEmerReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmerReportButtonActionPerformed
        // TODO add your handling code here:
        int pid = Integer.parseInt(packIdField.getText());

        lawEnforcementInspectorWorkRequest.getPackage1().setPackageStatus(statusField.getText());
        int did = lawEnforcementInspectorWorkRequest.getPackage1().getDisLotID();
        int mid = lawEnforcementInspectorWorkRequest.getPackage1().getManuLotID();
        int hid = lawEnforcementInspectorWorkRequest.getPackage1().getHosID();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getClass().equals(DistributorEnterprise.class)) {

                DistributorEnterprise distributorEnterprise = (DistributorEnterprise) enterprise;
                for (InventoryItem inventoryItem : distributorEnterprise.getInventoryCatalog().getInventoryList()) {
                    if (inventoryItem.getPackage1().getManuLotID() == mid) {
                        //System.out.println(""+mid);
                        // System.out.println(""+inventoryItem.getPackage1().getManuLotID());
                        inventoryItem.getPackage1().setPackageStatus("Illegetimate Drug");
                    }
                }

            }

            if (enterprise.getClass().equals(HospitalEnterprise.class)) {

                HospitalEnterprise hospitalEnterprise = (HospitalEnterprise) enterprise;
                for (InventoryItem inventoryItem : hospitalEnterprise.getInventoryCatalog().getInventoryList()) {

                    if (inventoryItem.getPackage1().getDisLotID() == did) {
                        inventoryItem.getPackage1().setPackageStatus("Illegetimate Drug");

                    }

                    if (!patientField.getText().isEmpty()) {

                        for (Transaction transaction : network.getTransactionHistory().getTransactionList()) {
                            if (transaction.getPackage().getPackageID() == lawEnforcementInspectorWorkRequest.getPackage1().getPackageID()) {
                                Doctor doc = transaction.getDoctor();

                                for (Package1 package1 : doc.getDrugCatalog().getPackPatientList()) {
                                    if (package1.getHosID() == hid) {
                                        package1.setPackageStatus("Illegetimate Drug");

                                    }
                                }
                            }
                        }

                    }
                }
            }

        }

        JOptionPane.showMessageDialog(null, "Emergency Report sent to the Enterprises");
    }//GEN-LAST:event_sendEmerReportButtonActionPerformed

    private void patientFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);

        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField dispenserNameField;
    private javax.swing.JTextField distField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField manuField;
    private javax.swing.JTextField packIdField;
    private javax.swing.JTextField patientField;
    private javax.swing.JButton sendEmerReportButton;
    private javax.swing.JTextField statusField;
    // End of variables declaration//GEN-END:variables
}
