/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InventoryManager;

import Business.WorkRequests.DrugTesterWorkRequest;
import Business.DrugTestingOrganization;
import Business.Enterprise;
import Business.FDAEnterprise;
import Business.HospitalEnterprise;
import Business.WorkRequests.InventoryManagerWorkRequest;
import Business.LotOfDrug;
import Business.Network;
import Business.Order;
import Business.Package1;
import Business.Transaction;
import Business.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bobba
 */
public class ViewSuspectDrugsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    InventoryManagerWorkRequest inventoryManagerWorkRequest;
    Network network;
    UserAccount userAccount;

    /**
     * Creates new form ViewSuspectDrugsJPanel
     */
    public ViewSuspectDrugsJPanel(JPanel userProcessContainer, InventoryManagerWorkRequest inventoryManagerWorkRequest, Network network, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.inventoryManagerWorkRequest = inventoryManagerWorkRequest;
        this.network = network;
        this.userAccount = userAccount;
        refresh();
    }

    public void refresh() {
        int rowcount = requestsTable.getRowCount();

        for (int i = rowcount - 1; i >= 0; i--) {
            ((DefaultTableModel) requestsTable.getModel()).removeRow(i);

        }

        for (Transaction transaction : network.getTransactionHistory().getTransactionList()) {
            Order ord = inventoryManagerWorkRequest.getOrder();

            for (LotOfDrug lotOfDrug : ord.getLotOfDrugsList()) {

                for (Package1 p : lotOfDrug.getPackageList()) {
                    if (transaction.getPackage().getPackageID() == p.getPackageID()) {
                        if (transaction.getManufacturerEnterprise() == null || transaction.getDistributorEnterprise() == null || transaction.getHospitalEnterprise() == null || transaction.getPackage().getPackageStatus().equalsIgnoreCase("Suspect Drug")) {
                            Object row[] = new Object[7];
                            row[0] = p.getPackageID();

                            ((DefaultTableModel) requestsTable.getModel()).addRow(row);

                        }

                    }
                }

            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestsTable = new javax.swing.JTable();
        reportFDAButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("View Suspect Drugs");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 11, -1, -1));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/backButton.jpg"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 41, 25));

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/refresh_button.jpg"))); // NOI18N
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 71, 24, 22));

        requestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Package ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 118, 364, 92));

        reportFDAButton.setText("Report FDA");
        reportFDAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportFDAButtonActionPerformed(evt);
            }
        });
        add(reportFDAButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void reportFDAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportFDAButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = requestsTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a work request");
            return;
        }

        Package1 p1 = (Package1) requestsTable.getValueAt(selectedRow, 0);

        DrugTesterWorkRequest drugTesterWorkRequest = new DrugTesterWorkRequest();
        drugTesterWorkRequest.setSender(userAccount);
        drugTesterWorkRequest.setRequestDate(new Date());
        drugTesterWorkRequest.setMessage("Test the Drug");
        drugTesterWorkRequest.setStatus("Drug under testing");
        drugTesterWorkRequest.setResultTest("Drug test");
        // drugTesterWorkRequest.setEnterprise(enterprise1);
        drugTesterWorkRequest.setPackage1(p1);

        Enterprise e = network.getEnterpriseDirectory().getMyEnterprise(userAccount);
        HospitalEnterprise hospitalEnterprise = (HospitalEnterprise) e;

        if (e.getClass().equals(HospitalEnterprise.class)) {

            FDAEnterprise e1 = null;
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise.getClass().equals(FDAEnterprise.class)) {
                    e1 = (FDAEnterprise) enterprise;
                }
            }

            DrugTestingOrganization drugTestingOrganization = e1.getDrugTestingOrganization();
            drugTestingOrganization.getWorkQueue().getWorkRequestList().add(drugTesterWorkRequest);

            // userAccount.getWorkQueue().getWorkRequestList().add(salesRequest);
            hospitalEnterprise.getInventoryManagementOrganization().getSentWorkQueue().getWorkRequestList().add(drugTesterWorkRequest);

            JOptionPane.showMessageDialog(null, "Work Request Sent");
        }
    }//GEN-LAST:event_reportFDAButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton reportFDAButton;
    private javax.swing.JTable requestsTable;
    // End of variables declaration//GEN-END:variables
}
