/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesManager;

import Business.DistributorEnterprise;
import Business.Drug;
import Business.Enterprise;
import Business.LotOfDrug;
import Business.Network;
import Business.Order;
import Business.Package1;
import Business.WorkRequests.SalesManagerWorkRequest;
import Business.UserAccount;
import Business.WorkRequests.WarehouseManagerWorkRequest;
import Business.WarehouseOrganization;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author srush
 */
public class OrderDrugJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    SalesManagerWorkRequest salesManagerWorkRequest;
    UserAccount userAccount;

    /**
     * Creates new form OrderDrugJPanel
     */
    public OrderDrugJPanel(JPanel userProcessContainer, Network network, SalesManagerWorkRequest salesManagerWorkRequest, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.salesManagerWorkRequest = salesManagerWorkRequest;
        this.userAccount = userAccount;
        distributorComboBox.removeAllItems();
        drugComboBox.removeAllItems();
        refresh();
    }
   
    public void refresh() {

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {

            if (enterprise.getClass().equals(DistributorEnterprise.class)) {
                //manufacturerComboBox.addItem(enterprise);
                DistributorEnterprise distributorEnterprise = (DistributorEnterprise) enterprise;

                distributorComboBox.addItem(enterprise);

            }

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        sendRequestButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        distributorComboBox = new javax.swing.JComboBox();
        drugComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(238, 238, 238));
        setMaximumSize(new java.awt.Dimension(1280, 700));
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setPreferredSize(new java.awt.Dimension(1280, 700));

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 40, 49));
        jLabel2.setText("DRUG NAME");

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 40, 49));
        jLabel3.setText("QUANTITY");

        quantityField.setBackground(new java.awt.Color(238, 238, 238));
        quantityField.setForeground(new java.awt.Color(34, 40, 49));
        quantityField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));
        quantityField.setMaximumSize(new java.awt.Dimension(200, 24));
        quantityField.setMinimumSize(new java.awt.Dimension(200, 24));
        quantityField.setPreferredSize(new java.awt.Dimension(200, 24));

        sendRequestButton.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        sendRequestButton.setForeground(new java.awt.Color(238, 238, 238));
        sendRequestButton.setText("SEND REQUEST");
        sendRequestButton.setMaximumSize(new java.awt.Dimension(150, 33));
        sendRequestButton.setMinimumSize(new java.awt.Dimension(150, 33));
        sendRequestButton.setPreferredSize(new java.awt.Dimension(150, 33));
        sendRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(238, 238, 238));
        backButton.setForeground(new java.awt.Color(238, 238, 238));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/back.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        backButton.setMaximumSize(new java.awt.Dimension(60, 60));
        backButton.setMinimumSize(new java.awt.Dimension(60, 60));
        backButton.setPreferredSize(new java.awt.Dimension(60, 60));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 40, 49));
        jLabel4.setText("SEND DRUG ORGER REQUEST TO INVENTORY MANAGER");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 173, 181)));

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 40, 49));
        jLabel5.setText("DISTRIBUTOR NAME");

        distributorComboBox.setBackground(new java.awt.Color(238, 238, 238));
        distributorComboBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        distributorComboBox.setForeground(new java.awt.Color(34, 40, 49));
        distributorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        distributorComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                distributorComboBoxItemStateChanged(evt);
            }
        });
        distributorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distributorComboBoxActionPerformed(evt);
            }
        });

        drugComboBox.setBackground(new java.awt.Color(238, 238, 238));
        drugComboBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        drugComboBox.setForeground(new java.awt.Color(34, 40, 49));
        drugComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jLabel4)))
                .addContainerGap(405, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50)
                        .addComponent(distributorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantityField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sendRequestButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(drugComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(479, 479, 479))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(distributorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addComponent(drugComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(sendRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestButtonActionPerformed
        // TODO add your handling code here:
        
        Drug drug = (Drug) drugComboBox.getSelectedItem();
        if (quantityField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the value for all fields");
        } else {

            if (quantityField.getText().isEmpty() == false) {
                try {
                    String stringPrice = quantityField.getText();
                    if (stringPrice.isEmpty() == false) {
                        int price = Integer.parseInt(stringPrice);

                    }

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Please enter proper value for quantity");
                    return;
                }

            }
            WarehouseManagerWorkRequest wareHouseManagerWorkRequest = new WarehouseManagerWorkRequest();
            wareHouseManagerWorkRequest.setSender(userAccount);
            wareHouseManagerWorkRequest.setRequestDate(new Date());
            wareHouseManagerWorkRequest.setMessage("Order for more drugs");
            wareHouseManagerWorkRequest.setStatus("warehouse low on drugs");
            //   wareHouseManagerWorkRequest.setManuName(manuNameField.getText());
            wareHouseManagerWorkRequest.setDrName(drug.getDrugName());
            wareHouseManagerWorkRequest.setDrug(drug);
            wareHouseManagerWorkRequest.setResult("Sent for ordering");
            wareHouseManagerWorkRequest.setQuantity(Integer.parseInt(quantityField.getText()));


            DistributorEnterprise e = (DistributorEnterprise) network.getEnterpriseDirectory().getMyEnterprise(userAccount);

            DistributorEnterprise e1 = null;
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise.getClass().equals(DistributorEnterprise.class)) {
                    e1 = (DistributorEnterprise) enterprise;
                }
            }

            WarehouseOrganization warehouseOrganization = e1.getWarehouseOrganization();
            warehouseOrganization.getWorkQueue().getWorkRequestList().add(wareHouseManagerWorkRequest);

            // userAccount.getWorkQueue().getWorkRequestList().add(salesRequest);
            e.getSalesManagementOrganization().getSentWorkQueue().getWorkRequestList().add(wareHouseManagerWorkRequest);

            JOptionPane.showMessageDialog(null, "Work Request Sent");
        }
    }//GEN-LAST:event_sendRequestButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void distributorComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_distributorComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_distributorComboBoxItemStateChanged

    private void distributorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distributorComboBoxActionPerformed
        // TODO add your handling code here:
        DistributorEnterprise distributorEnterprise = (DistributorEnterprise) distributorComboBox.getSelectedItem();

        if (distributorEnterprise != null) {
            drugComboBox.removeAllItems();
            for (Drug drug : distributorEnterprise.getDrugCatalog().getDrugList()) {
                drugComboBox.addItem(drug);
            }
        }
    }//GEN-LAST:event_distributorComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox distributorComboBox;
    private javax.swing.JComboBox drugComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton sendRequestButton;
    // End of variables declaration//GEN-END:variables
}
