/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospitalManager;

import Business.Address;
import Business.Enterprise;
import Business.HospitalEnterprise;
import Business.Network;
import Business.Organization;
import Business.Doctor;
import Business.Roles.DoctorRole;
import Business.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author srush
 */
public class AddDoctorJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    UserAccount userAccount;

    /**
     * Creates new form AddPatientJPanel
     */
    public AddDoctorJPanel(JPanel userProcessContainer, Network network, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.userAccount = userAccount;
        hospJCombo.removeAllItems();
        refresh();
    }

    public void refresh() {

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {

            if (enterprise.getClass().equals(HospitalEnterprise.class)) {
                HospitalEnterprise hospital = (HospitalEnterprise) enterprise;

                hospJCombo.addItem(enterprise);

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        addDoctorButton = new javax.swing.JButton();
        stateField = new javax.swing.JTextField();
        zipcodeField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        line2Field = new javax.swing.JTextField();
        LicenseNoField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        hospJCombo = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(238, 238, 238));
        setMaximumSize(new java.awt.Dimension(1280, 700));
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1280, 700));

        jLabel1.setBackground(new java.awt.Color(238, 238, 238));
        jLabel1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 40, 49));
        jLabel1.setText("ADD DOCTOR PROFILE");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 173, 181)));

        jLabel2.setBackground(new java.awt.Color(238, 238, 238));
        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 40, 49));
        jLabel2.setText("FIRST NAME");

        jLabel3.setBackground(new java.awt.Color(238, 238, 238));
        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 40, 49));
        jLabel3.setText("LAST NAME");

        jLabel4.setBackground(new java.awt.Color(238, 238, 238));
        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 40, 49));
        jLabel4.setText("HOSPITAL NAME");

        jLabel5.setBackground(new java.awt.Color(238, 238, 238));
        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 40, 49));
        jLabel5.setText("CREATE USERNAME");

        jLabel6.setBackground(new java.awt.Color(238, 238, 238));
        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 40, 49));
        jLabel6.setText("CREATE PASSWORD");

        firstNameField.setBackground(new java.awt.Color(238, 238, 238));
        firstNameField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        firstNameField.setForeground(new java.awt.Color(34, 40, 49));
        firstNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));

        lastNameField.setBackground(new java.awt.Color(238, 238, 238));
        lastNameField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lastNameField.setForeground(new java.awt.Color(34, 40, 49));
        lastNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));

        userNameField.setBackground(new java.awt.Color(238, 238, 238));
        userNameField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        userNameField.setForeground(new java.awt.Color(34, 40, 49));
        userNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));

        passwordField.setBackground(new java.awt.Color(238, 238, 238));
        passwordField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        passwordField.setForeground(new java.awt.Color(34, 40, 49));
        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));

        backButton.setBackground(new java.awt.Color(238, 238, 238));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/back.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addDoctorButton.setBackground(new java.awt.Color(57, 62, 70));
        addDoctorButton.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        addDoctorButton.setForeground(new java.awt.Color(238, 238, 238));
        addDoctorButton.setText("CREATE DOCTOR PROFILE");
        addDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorButtonActionPerformed(evt);
            }
        });

        stateField.setBackground(new java.awt.Color(238, 238, 238));
        stateField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stateField.setForeground(new java.awt.Color(34, 40, 49));
        stateField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));

        zipcodeField.setBackground(new java.awt.Color(238, 238, 238));
        zipcodeField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        zipcodeField.setForeground(new java.awt.Color(34, 40, 49));
        zipcodeField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));

        cityField.setBackground(new java.awt.Color(238, 238, 238));
        cityField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        cityField.setForeground(new java.awt.Color(34, 40, 49));
        cityField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));
        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });

        line2Field.setBackground(new java.awt.Color(238, 238, 238));
        line2Field.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        line2Field.setForeground(new java.awt.Color(34, 40, 49));
        line2Field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));

        LicenseNoField.setBackground(new java.awt.Color(238, 238, 238));
        LicenseNoField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        LicenseNoField.setForeground(new java.awt.Color(34, 40, 49));
        LicenseNoField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));

        jLabel12.setBackground(new java.awt.Color(238, 238, 238));
        jLabel12.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(34, 40, 49));
        jLabel12.setText("ZIPCODE");

        jLabel11.setBackground(new java.awt.Color(238, 238, 238));
        jLabel11.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(34, 40, 49));
        jLabel11.setText("STATE");

        jLabel10.setBackground(new java.awt.Color(238, 238, 238));
        jLabel10.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(34, 40, 49));
        jLabel10.setText("CITY");

        jLabel9.setBackground(new java.awt.Color(238, 238, 238));
        jLabel9.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(34, 40, 49));
        jLabel9.setText("ADDRESS");

        jLabel8.setBackground(new java.awt.Color(238, 238, 238));
        jLabel8.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(34, 40, 49));
        jLabel8.setText("LICENSE NUMBER");

        jLabel7.setBackground(new java.awt.Color(238, 238, 238));
        jLabel7.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(34, 40, 49));
        jLabel7.setText("HOME ADDRESS:");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 173, 181)));

        jLabel13.setBackground(new java.awt.Color(238, 238, 238));
        jLabel13.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(34, 40, 49));
        jLabel13.setText("PERSONAL DETAILS:");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 173, 181)));

        hospJCombo.setBackground(new java.awt.Color(238, 238, 238));
        hospJCombo.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        hospJCombo.setForeground(new java.awt.Color(34, 40, 49));
        hospJCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        hospJCombo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hospJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(200, 200, 200)
                                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(line2Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(160, 160, 160)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LicenseNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(zipcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(541, 541, 541)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(addDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LicenseNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(zipcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hospJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(line2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(addDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorButtonActionPerformed
        // TODO add your handling code here:

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {

            for (Organization organization : enterprise.getOrganizationDirectory().getOrgList()) {
                for (UserAccount userAccount1 : organization.getUserAccountDirectory().getUserAccountList()) {
                    if (userAccount == userAccount1) {
                        if (firstNameField.getText().isEmpty() || lastNameField.getText().isEmpty() || userNameField.getText().isEmpty() || passwordField.getText().isEmpty()
                                || LicenseNoField.getText().isEmpty() || line2Field.getText().isEmpty() || cityField.getText().isEmpty() || zipcodeField.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Please fill all the fields");
                        } else {

                            if (!network.getEnterpriseDirectory().isUserExisting(userNameField.getText())) {
                                if (passwordPattern() == true) {
                                    HospitalEnterprise hospitalEnterprise = (HospitalEnterprise) enterprise;
                                    Doctor doc = hospitalEnterprise.getDoctorDirectory().newDoctor();
                                    doc.setFirstName(firstNameField.getText());
                                    doc.setLastName(lastNameField.getText());
                                    doc.setHsopName(hospJCombo.getSelectedItem().toString());

                                    Address address = doc.getAddress();
                                    address.setLine1(LicenseNoField.getText());
                                    address.setLine2(line2Field.getText());
                                    address.setCity(cityField.getText());
                                    address.setState(stateField.getText());
                                    address.setZipcode(zipcodeField.getText());

                                    UserAccount userAccount2 = hospitalEnterprise.getUserAccountDirectory().newAccount();
                                    userAccount2.setUserName(userNameField.getText());
                                    userAccount2.setPassword(passwordField.getText());
                                    userAccount2.setRole(new DoctorRole());
                                    userAccount2.setDoctor(doc);

                                    JOptionPane.showMessageDialog(null, "Doctor added");

                                    firstNameField.setText("");
                                    lastNameField.setText("");
                                    userNameField.setText("");
                                    passwordField.setText("");

                                    LicenseNoField.setText("");
                                    line2Field.setText("");
                                    cityField.setText("");
                                    stateField.setText("");
                                    zipcodeField.setText("");
                                } else {
                                    JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, "
                                            + "one lower case letter, one digit and one special character $, *, # or &.");
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "User Name already present");
                            }

                        }

                    }
                }
            }
        }

    }//GEN-LAST:event_addDoctorButtonActionPerformed

    private boolean passwordPattern() {
        Pattern p = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m = p.matcher(passwordField.getText());
        boolean b = m.matches();
        return b;
    }

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);

        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LicenseNoField;
    private javax.swing.JButton addDoctorButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JComboBox hospJCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField line2Field;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField stateField;
    private javax.swing.JTextField userNameField;
    private javax.swing.JTextField zipcodeField;
    // End of variables declaration//GEN-END:variables
}
