/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospitalManager;

import Business.Business;
import Business.Enterprise;
import Business.Network;
import Business.Organization;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author bobba
 */
public class HospitalManagerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Business business;
    UserAccount userAccount;

    /**
     * Creates new form HospitalManagerJPanel
     */
    public HospitalManagerJPanel(JPanel userProcessContainer, Business business, UserAccount userAccount) {
        initComponents();

        // hospitalLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/hospital.jpg")));
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageDoctorBtn = new javax.swing.JButton();
        addDoctorBtn = new javax.swing.JButton();
        viewReportedIncidentsButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Hospital Manager Work Area");

        manageDoctorBtn.setText("Manage Doctor");
        manageDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDoctorBtnActionPerformed(evt);
            }
        });

        addDoctorBtn.setText("Add Doctors");
        addDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorBtnActionPerformed(evt);
            }
        });

        viewReportedIncidentsButton.setText("View Reported Incidents");
        viewReportedIncidentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportedIncidentsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(viewReportedIncidentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addDoctorBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageDoctorBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(addDoctorBtn)
                .addGap(18, 18, 18)
                .addComponent(manageDoctorBtn)
                .addGap(18, 18, 18)
                .addComponent(viewReportedIncidentsButton)
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorBtnActionPerformed
        // TODO add your handling code here:
        for (Network network : business.getNetworkDirectory().getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrgList()) {
                    for (UserAccount userAccount1 : organization.getUserAccountDirectory().getUserAccountList()) {
                        if (userAccount == userAccount1) {

                            AddDoctorJPanel addDoctorJPanel = new AddDoctorJPanel(userProcessContainer, network, userAccount);
                            userProcessContainer.add("AddDoctor", addDoctorJPanel);

                            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
                            cardLayout.next(userProcessContainer);

                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_addDoctorBtnActionPerformed

    private void viewReportedIncidentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportedIncidentsButtonActionPerformed
        // TODO add your handling code here:

        for (Network network : business.getNetworkDirectory().getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrgList()) {
                    for (UserAccount userAccount1 : organization.getUserAccountDirectory().getUserAccountList()) {
                        if (userAccount == userAccount1) {

                            ReportedIncidentsJPanel reportedIncidentsJPanel = new ReportedIncidentsJPanel(userProcessContainer, network, userAccount);
                            userProcessContainer.add("ReportInc", reportedIncidentsJPanel);

                            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
                            cardLayout.next(userProcessContainer);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_viewReportedIncidentsButtonActionPerformed

    private void manageDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDoctorBtnActionPerformed
        // TODO add your handling code here:

        for (Network network : business.getNetworkDirectory().getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrgList()) {
                    for (UserAccount userAccount1 : organization.getUserAccountDirectory().getUserAccountList()) {
                        if (userAccount == userAccount1) {

                            ManageDoctorJPanel manageDoctorJPanel = new ManageDoctorJPanel(userProcessContainer, network, userAccount);
                            userProcessContainer.add("manageDoctor", manageDoctorJPanel);

                            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
                            cardLayout.next(userProcessContainer);

                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_manageDoctorBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDoctorBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageDoctorBtn;
    private javax.swing.JButton viewReportedIncidentsButton;
    // End of variables declaration//GEN-END:variables
}
