/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospitalManager;

import Business.WorkRequests.DrugTesterWorkRequest;
import Business.DrugTestingOrganization;
import Business.Enterprise;
import Business.FDAEnterprise;
import Business.HospitalEnterprise;
import Business.InventoryItem;
import Business.WorkRequests.ManagerWorkRequest;
import Business.Network;
import Business.Organization;
import Business.UserAccount;
import Business.WorkRequests.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bobba
 */
public class ReportedIncidentsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    UserAccount userAccount;

    /**
     * Creates new form ReportedIncidentsJPanel
     */
    public ReportedIncidentsJPanel(JPanel userProcessContainer, Network network, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.userAccount = userAccount;
        refresh();
    }

    public void refresh() {
        int rowcount = requestsTable.getRowCount();

        for (int i = rowcount - 1; i >= 0; i--) {
            ((DefaultTableModel) requestsTable.getModel()).removeRow(i);

        }

        Enterprise e = network.getEnterpriseDirectory().getMyEnterprise(userAccount);

        if (e.getClass().equals(HospitalEnterprise.class)) {
            HospitalEnterprise hospitalEnterprise = (HospitalEnterprise) e;
            Organization org = ((HospitalEnterprise) e).getManagementOrganization();
            for (WorkRequest workRequest : org.getWorkQueue().getWorkRequestList()) {
                ManagerWorkRequest managerWokrRequest = (ManagerWorkRequest) workRequest;
                Object row[] = new Object[7];
                row[0] = workRequest;
                row[1] = workRequest.getSender();

                if (workRequest.getReceiver() != null) {
                    row[2] = workRequest.getReceiver().getEmployee().getFirstName() + " " + workRequest.getReceiver().getEmployee().getLastName();

                }

                row[3] = workRequest.getStatus();
                row[4] = hospitalEnterprise.getEnterpriseName();
                row[5] = managerWokrRequest.getDgName();
                row[6] = managerWokrRequest.getProblemReported();
                //  row[4]=workRequest.getDrugName();
                //  row[5]=workRequest.getQuantity();

                ((DefaultTableModel) requestsTable.getModel()).addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestsTable = new javax.swing.JTable();
        assignButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        reportFDAButton = new javax.swing.JButton();

        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        requestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Enterprise Name", "Drug Name", "Problem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestsTable);

        assignButton.setText("Assign to me");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("View Requests");

        reportFDAButton.setText("Report FDA");
        reportFDAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportFDAButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignButton)
                                .addGap(255, 255, 255)
                                .addComponent(reportFDAButton))
                            .addComponent(refreshButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(151, 151, 151))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportFDAButton)
                    .addComponent(assignButton))
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        // TODO add your handling code here:

        int row = requestsTable.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a work request");
            return;
        }

        WorkRequest workRequest = (WorkRequest) requestsTable.getValueAt(row, 0);

        if (workRequest.getReceiver() == null) {

            workRequest.setReceiver(userAccount);

            workRequest.setStatus("Pending");

            refresh();
        } else {
            JOptionPane.showMessageDialog(this, "The task is already assigned to other person");
        }
    }//GEN-LAST:event_assignButtonActionPerformed

    private void reportFDAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportFDAButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = requestsTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a work request");
            return;
        }
        WorkRequest workRequest = (WorkRequest) requestsTable.getValueAt(selectedRow, 0);

        if (workRequest.getReceiver() != null) {

            workRequest.setReceiver(userAccount);

            workRequest.setStatus("Sent To FDA tester");
            refresh();
        }

        ManagerWorkRequest managerWokrRequest = (ManagerWorkRequest) requestsTable.getValueAt(selectedRow, 0);

        if (managerWokrRequest.getReceiver() != null && userAccount == managerWokrRequest.getReceiver()) {
            // Enterprise e5=network.getEnterpriseDirectory().getMyEnterprise(userAccount);
            // HospitalEnterprise hospitalEnterprise=(HospitalEnterprise)e5;

            DrugTesterWorkRequest drugTesterWorkRequest = new DrugTesterWorkRequest();
            drugTesterWorkRequest.setSender(userAccount);
            drugTesterWorkRequest.setRequestDate(new Date());
            drugTesterWorkRequest.setMessage("Test the Drug");
            drugTesterWorkRequest.setStatus("Drug under testing");
            // licenseManagerWorkRequest.setManuName(manuNameField.getText());
            // licenseManagerWorkRequest.setDrugManu(drugaManuTextArea.getText());
            drugTesterWorkRequest.setResultTest("Drug test");
            //drugTesterWorkRequest.setDrug(managerWokrRequest.getDrug());
            // drugTesterWorkRequest.setEnterprise(network);

            Enterprise e = network.getEnterpriseDirectory().getMyEnterprise(userAccount);

            if (e.getClass().equals(HospitalEnterprise.class)) {
                HospitalEnterprise hospitalEnterprise = (HospitalEnterprise) e;
                FDAEnterprise e1 = null;
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise.getClass().equals(FDAEnterprise.class)) {
                        e1 = (FDAEnterprise) enterprise;
                    }
                }

                /*  for(InventoryItem itm:hospitalEnterprise.getInventoryCatalog().getInventoryList())
        {
            if(itm.getPackage1().getPackageID()==managerWokrRequest.getPackID())
            {
                drugTesterWorkRequest.setPackage1(itm.getPackage1());
                
            }
            
        }*/
                drugTesterWorkRequest.setEnterprise(hospitalEnterprise);
                drugTesterWorkRequest.setPackage1(managerWokrRequest.getPackage1());
                DrugTestingOrganization drugTestingOrganization = e1.getDrugTestingOrganization();
                drugTestingOrganization.getWorkQueue().getWorkRequestList().add(drugTesterWorkRequest);

                // userAccount.getWorkQueue().getWorkRequestList().add(salesRequest);
                hospitalEnterprise.getManagementOrganization().getSentWorkQueue().getWorkRequestList().add(drugTesterWorkRequest);

                JOptionPane.showMessageDialog(null, "Work Request Sent");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please assign it and then proceed/Task might be assigned to other person");
        }
    }//GEN-LAST:event_reportFDAButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton reportFDAButton;
    private javax.swing.JTable requestsTable;
    // End of variables declaration//GEN-END:variables
}
