/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Business;
import Business.ConfigureABusiness;
import Business.Enterprise;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author srush
 */
public class MainJFrame extends javax.swing.JFrame {
    
     Business business;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
       // business=ConfigureABusiness.initialize();
        
        business=db4o.db4oUtil.getBusiness();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        mainJSpliPane.setLeftComponent(new LoginJPanel(this));
        
    }
    public Business getBusiness(){
    return business;
    }
    
    
     public void loginUser(String username, String password, Enterprise enterprise) {

        UserAccount ua = enterprise.authenticateUser(username, password);
        if (ua != null) {
            
            //
            mainJSpliPane.setLeftComponent(new LogoutJPanel(this, ua,userProcessContainer));
            
            userProcessContainer.removeAll();
            JPanel panel = ua.getRole().getWorkArea().createView(userProcessContainer, business, ua).getViewPanel();
            userProcessContainer.add("WorkArea", panel);
            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password");            
        }
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt)
{
    
    db4o.db4oUtil.storeObject(business);
}
    
     public void logoutUser(JPanel userProcessContainer) {
        // do any cleanup here
        // do any cleanup here
        db4o.db4oUtil.storeObject(business);
        // set login jpanel
         
         userProcessContainer.removeAll();
         userProcessContainer.repaint();
         mainJSpliPane.setLeftComponent(new LoginJPanel(this));
    }
    
     /*private void formWindowClosing(java.awt.event.WindowEvent evt)
{
    
    db4o.db4oUtil.storeObject(business);
}*/
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJSpliPane = new javax.swing.JSplitPane();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        mainJSpliPane.setRightComponent(userProcessContainer);

        getContentPane().add(mainJSpliPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane mainJSpliPane;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
