/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LicenseInspectorRole;

import Business.Enterprise;
import Business.FDAEnterprise;
import Business.WorkRequests.LicenseManagerWorkRequest;
import Business.Network;
import Business.Organization;
import Business.StateRegulatoryEnterprise;
import Business.UserAccount;
import Business.WorkRequests.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srush
 */
public class ApproveLicensesJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Network network;
    UserAccount userAccount;

    /**
     * Creates new form ApproveLicensesJPanel
     */
    public ApproveLicensesJPanel(JPanel userProcessContainer,Network network,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.network=network;
        this.userAccount=userAccount;
        Refresh();
    }
    
    
    public void Refresh()
    {
        
        
        
        int rowcount=requestsTable.getRowCount();
        
        for(int i=rowcount-1;i>=0;i--)
        {
            ((DefaultTableModel)requestsTable.getModel()).removeRow(i);
            
            
            
        }
        
        Enterprise e=network.getEnterpriseDirectory().getMyEnterprise(userAccount);
       
        if(e.getClass().equals(FDAEnterprise.class))
        {
       Organization org=((FDAEnterprise)e).getLicensingOrganization();
       
       
        for(WorkRequest workRequest:org.getWorkQueue().getWorkRequestList())
                
        {
            LicenseManagerWorkRequest licenseManagerWorkRequest=(LicenseManagerWorkRequest)workRequest;
         Object row[]=new Object[6];
         row[0]=workRequest;
         row[1]=workRequest.getSender().getEmployee().getFirstName();
         
         if(workRequest.getReceiver()!= null)
         {
         row[2]=workRequest.getReceiver().getEmployee().getFirstName();
         
         }
         
         row[3]=workRequest.getStatus();
        row[4]=licenseManagerWorkRequest.getManuName();
        row[5]=licenseManagerWorkRequest.getDrugManu();
         
         
            
            
            
           ((DefaultTableModel)requestsTable.getModel()).addRow(row);   
        }
        }
        else if(e.getClass().equals(StateRegulatoryEnterprise.class))
        {
       Organization org=((StateRegulatoryEnterprise)e).getLicensingOrganization();
       
       
        for(WorkRequest workRequest:org.getWorkQueue().getWorkRequestList())
                
        {
            LicenseManagerWorkRequest licenseManagerWorkRequest=(LicenseManagerWorkRequest)workRequest;
         Object row[]=new Object[6];
         row[0]=workRequest;
         row[1]=workRequest.getSender().getEmployee().getFirstName();
         
         if(workRequest.getReceiver()!= null)
         {
         row[2]=workRequest.getReceiver().getEmployee().getFirstName();
         
         }
         
         row[3]=workRequest.getStatus();
        row[4]=licenseManagerWorkRequest.getManuName();
        row[5]=licenseManagerWorkRequest.getDrugManu();
         
         
            
            
            
           ((DefaultTableModel)requestsTable.getModel()).addRow(row);   
        }
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestsTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        approveLicenseButton = new javax.swing.JButton();
        assignButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        requestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Manufacturer Name", "Drug Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestsTable);

        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        approveLicenseButton.setText("Approve License");
        approveLicenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveLicenseButtonActionPerformed(evt);
            }
        });

        assignButton.setText("Assign to me");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Work Requests");

        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(assignButton)
                            .addGap(248, 248, 248)
                            .addComponent(approveLicenseButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveLicenseButton)
                    .addComponent(assignButton))
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        Refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void approveLicenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveLicenseButtonActionPerformed
        // TODO add your handling code here:
       int selectedRow=requestsTable.getSelectedRow();

        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null, "Please select a work request");
            return;
        }

        LicenseManagerWorkRequest licenseManagerWorkRequest=(LicenseManagerWorkRequest)requestsTable.getValueAt(selectedRow, 0);
        
        if(licenseManagerWorkRequest.getReceiver()!=null && userAccount==licenseManagerWorkRequest.getReceiver())
        {
          if(licenseManagerWorkRequest.getStatus() != "License Approved")
          {
        ApproveLicenseRequestsJPanel approveLicenseRequestsJPanel=new ApproveLicenseRequestsJPanel(userProcessContainer,licenseManagerWorkRequest,userAccount,network);
        userProcessContainer.add("APPLIC",approveLicenseRequestsJPanel);

        CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        }
          else
          {
              JOptionPane.showMessageDialog(null,"License Request has already been handled");
          }
          
        }
        
        else
       {
           JOptionPane.showMessageDialog(this, "Please assign it and then proceed/Task might be assigned to other person");
       }
    }//GEN-LAST:event_approveLicenseButtonActionPerformed

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        // TODO add your handling code here:

        int row=requestsTable.getSelectedRow();

        if(row<0)
        {
            JOptionPane.showMessageDialog(null, "Please select a work request");
            return;
        }

        WorkRequest workRequest=(WorkRequest)requestsTable.getValueAt(row, 0);

        if(workRequest.getReceiver()== null)
        {

            workRequest.setReceiver(userAccount);

            workRequest.setStatus("Pending");

            Refresh();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "The task is already assigned to other person");
        }
    }//GEN-LAST:event_assignButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveLicenseButton;
    private javax.swing.JButton assignButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable requestsTable;
    // End of variables declaration//GEN-END:variables
}
