/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Doctor;

import Business.Drug;
import Business.Enterprise;
import Business.HospitalEnterprise;
import Business.InventoryItem;
import Business.ManagementOrganization;
import Business.WorkRequests.ManagerWorkRequest;
import Business.Network;
import Business.Package1;
import Business.Doctor;
import Business.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nived
 */
public class ReportAnIncidentJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    UserAccount userAccount;

    /**
     * Creates new form ReportAnIncidentJPane
     */
    public ReportAnIncidentJPanel(JPanel userProcessContainer, Network network, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.userAccount = userAccount;
        dispenserNameComboBox.removeAllItems();
        packComboBox.removeAllItems();
        drugComboBox.removeAllItems();
        //drugNameComboBox.removeAllItems();
        refresh();
    }

    public void refresh() {

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getClass().equals(HospitalEnterprise.class)) {
                HospitalEnterprise hospitalEnterprise = (HospitalEnterprise) enterprise;
                dispenserNameComboBox.addItem(hospitalEnterprise);
            }

        }
        Doctor doc = userAccount.getDoctor();
        Package1 tempPackage = null;
        Set<String> drugNames = new HashSet<>();
        for (Package1 package1 : doc.getDrugCatalog().getPackDoctorList()) {
            if (drugNames.add(package1.getDrug().getDrugName())) {
                drugComboBox.addItem(package1.getDrug().getDrugName());
            }
            //drugComboBox.addItem(package1.getDrug().getDrugName());
            packComboBox.addItem(package1.getPackageID());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dispenserNameComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTextArea = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        packComboBox = new javax.swing.JComboBox();
        drugComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(238, 238, 238));
        setMaximumSize(new java.awt.Dimension(1280, 700));
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setPreferredSize(new java.awt.Dimension(1280, 700));

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 40, 49));
        jLabel1.setText("Report Problem");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 173, 181)));

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 40, 49));
        jLabel2.setText("MANUFACTURE");

        dispenserNameComboBox.setBackground(new java.awt.Color(238, 238, 238));
        dispenserNameComboBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        dispenserNameComboBox.setForeground(new java.awt.Color(34, 40, 49));
        dispenserNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dispenserNameComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));
        dispenserNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispenserNameComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 40, 49));
        jLabel3.setText("DRUG NAME");

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 40, 49));
        jLabel4.setText("DETAILS");

        detailsTextArea.setBackground(new java.awt.Color(238, 238, 238));
        detailsTextArea.setColumns(20);
        detailsTextArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        detailsTextArea.setForeground(new java.awt.Color(34, 40, 49));
        detailsTextArea.setRows(5);
        detailsTextArea.setMaximumSize(new java.awt.Dimension(200, 80));
        detailsTextArea.setMinimumSize(new java.awt.Dimension(200, 80));
        detailsTextArea.setPreferredSize(new java.awt.Dimension(200, 80));
        jScrollPane1.setViewportView(detailsTextArea);

        backButton.setBackground(new java.awt.Color(238, 238, 238));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/back.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        reportButton.setBackground(new java.awt.Color(57, 62, 70));
        reportButton.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        reportButton.setForeground(new java.awt.Color(238, 238, 238));
        reportButton.setText("SUBMIT REPORT");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 40, 49));
        jLabel5.setText("PACKAGE ID");

        packComboBox.setBackground(new java.awt.Color(238, 238, 238));
        packComboBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        packComboBox.setForeground(new java.awt.Color(34, 40, 49));
        packComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        packComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));

        drugComboBox.setBackground(new java.awt.Color(238, 238, 238));
        drugComboBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        drugComboBox.setForeground(new java.awt.Color(34, 40, 49));
        drugComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drugComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 173, 181), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGap(50, 50, 50)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(packComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dispenserNameComboBox, 0, 200, Short.MAX_VALUE)
                                        .addComponent(drugComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(563, 563, 563)
                        .addComponent(jLabel1)))
                .addContainerGap(471, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dispenserNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(drugComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dispenserNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispenserNameComboBoxActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_dispenserNameComboBoxActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        // TODO add your handling code here:

        // InventoryItem inventoryItem=(InventoryItem)drugNameComboBox.getSelectedItem();
        // int pid=(Integer)drugNameComboBox.getSelectedItem();
        Enterprise enterprise = (Enterprise) dispenserNameComboBox.getSelectedItem();

        if (enterprise.getClass().equals(HospitalEnterprise.class)) {
            Doctor doc = userAccount.getDoctor();
            String drugName = drugComboBox.getSelectedItem().toString();

            ManagerWorkRequest managerWorkRequest = new ManagerWorkRequest();
            managerWorkRequest.setSender(userAccount);
            managerWorkRequest.setRequestDate(new Date());
            managerWorkRequest.setStatus("Problem Reported");
            managerWorkRequest.setResult("Problem reported");
            // managerWokrRequest.setLicenseNumber(Integer.parseInt(licenseNumberField.getText()));
            managerWorkRequest.setMessage("Problem Reported");

            //  managerWokrRequest.setDrug(inventoryItem.getDrug());
            // managerWokrRequest.setPackage1();
            managerWorkRequest.setProblemReported(detailsTextArea.getText());
            managerWorkRequest.setDgName(drugName);
            // managerWokrRequest.setPackID(Integer.parseInt(packageIDField.getText()));
            int pid = (Integer) packComboBox.getSelectedItem();

            for (Package1 package1 : doc.getDrugCatalog().getPackDoctorList()) {
                if (package1.getPackageID() == pid) {
                    managerWorkRequest.setPackage1(package1);
                }
            }

            HospitalEnterprise e = (HospitalEnterprise) network.getEnterpriseDirectory().getMyEnterprise(userAccount);

            //userAccount.getWorkQueue().getWorkRequestList().add(shipWorkRequest);
            JOptionPane.showMessageDialog(null, "Incident report sent to Hospital management successfully");

            HospitalEnterprise d1 = null;
            for (Enterprise enterprise1 : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise1.getClass().equals(HospitalEnterprise.class)) {
                    d1 = (HospitalEnterprise) enterprise1;
                }
            }

            ManagementOrganization managementOrganization = d1.getManagementOrganization();
            managementOrganization.getWorkQueue().getWorkRequestList().add(managerWorkRequest);
            JOptionPane.showMessageDialog(null, "Work Request Sent");
            //SalesManagementOrganization salesOrganization=e1.getSalesManagementOrganization();
            //  salesOrganization.getWorkQueue().getWorkRequestList().add(salesRequest);

            // userAccount.getWorkQueue().getWorkRequestList().add(salesRequest);
            //e.getLicensingOrganization().getSentWorkQueue().getWorkRequestList().add(managerWokrRequest);
        }


    }//GEN-LAST:event_reportButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea detailsTextArea;
    private javax.swing.JComboBox dispenserNameComboBox;
    private javax.swing.JComboBox drugComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox packComboBox;
    private javax.swing.JButton reportButton;
    // End of variables declaration//GEN-END:variables
}
