/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WarehouseManager;

import Business.DistributorEnterprise;
import Business.Drug;
import Business.Enterprise;
import Business.InventoryItem;
import Business.Network;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nived
 */
public class CheckWarehouseInventoryJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    UserAccount userAccount;

    /**
     * Creates new form CheckWarehouseInventoryJPanel
     */
    public CheckWarehouseInventoryJPanel(JPanel userProcessContainer, Network network, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.userAccount = userAccount;
        //inventoryDetailsComboBox.removeAllItems();
        // inventoryDetailsComboBox.addItem("All Inventory");

        // inventoryDetailsComboBox.addItem("Short Supply");
//        thresholdField.setText("5");
//        thresholdField.setEditable(false);
        refresh();
    }

    public void refresh() {

        int rowcount = inventoryReportTable.getRowCount();

        for (int i = rowcount - 1; i >= 0; i--) {
            ((DefaultTableModel) inventoryReportTable.getModel()).removeRow(i);
        }

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {

            if (enterprise.getClass().equals(DistributorEnterprise.class)) {

                DistributorEnterprise distributorEnterprise = (DistributorEnterprise) enterprise;
                //thresholdField.setText(Integer.toString(distributorEnterprise.getThreshold()));
                Drug tempDrug = null;
                for (InventoryItem inventoryItem : distributorEnterprise.getInventoryCatalog().getInventoryList()) {

                    // Drug drug=inventoryItem.getDrug();
                    // System.out.println(""+inventoryItem);
                    //   int price=product.getPrice();
                    Object row[] = new Object[3];

                    if (inventoryItem.getPackage1().getDrug() == tempDrug) {
                        break;
                    } else {
                        row[0] = inventoryItem.getPackage1();
                        //Drug drug=inventoryItem.getPackage1().getPackageID();
                        row[1] = distributorEnterprise.getInventoryCatalog().getTotalQuantity(inventoryItem.getPackage1().getDrug());
                        tempDrug = inventoryItem.getPackage1().getDrug();
                    }

                    //  row[1]=storeInventory.getTotalInventory(drug);
                    //  row[1]=masterOrderCatalog.getTotalNumber(product);
                    //row[2]=price*(masterOrderCatalog.getTotalNumber(product));
                    ((DefaultTableModel) inventoryReportTable.getModel()).addRow(row);

                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryReportTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 238, 238));
        setMaximumSize(new java.awt.Dimension(1280, 700));
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setPreferredSize(new java.awt.Dimension(1280, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Drug Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(inventoryReportTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 85, -1, 112));

        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 20, 40, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Manage Inventory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 24, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable inventoryReportTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
